FROM hexpm/elixir:1.14.3-erlang-25.2.1-debian-buster-20230109-slim

MAINTAINER Luca Zulian <info@lucazulian.it>

# install build dependencies
RUN apt-get update -y && apt-get install -y build-essential git inotify-tools \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

RUN mix local.hex --force && mix local.rebar --force

ENV ERL_AFLAGS "-kernel shell_history enabled"
