version: "3.9"

services:
  game:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: game-dev:latest
    security_opt:
      - seccomp:unconfined
    working_dir: /app
    command: tail -f /dev/null
    #command: mix serve
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - ./.volumes/game/_build:/app/_build
      - ./.volumes/game/deps:/app/deps
